---
# ansible-navigator run main.yaml -i inventory.yaml --pae false --mode stdout \
# --eei quay.io/jealopez/ee-ocp:1.3 -e "@credentials.vault.yaml" --vault-password-file=vault_password

- name: Ejecutar Must Gather
  import_playbook: playbooks/generate_must_gather.yaml

- name: Subir Must Gather a Red Hat
  import_playbook: playbooks/upload_must_gather.yaml

- name: Cerrar sesión en OpenShift (revocar token)
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all.yaml
    - ../credentials.vault.yaml
  tasks:
    - name: Cerrar sesión en OpenShift
      block:
        - name: Revocar el token de sesión en OpenShift
          redhat.openshift.openshift_auth:
            state: absent
            host: "{{ openshift_api_url }}"
            api_key: "{{ openshift_api_token }}"
            validate_certs: false
          when: openshift_api_token is defined
      rescue:
        - name: Advertencia si no se puede cerrar sesión
          ansible.builtin.debug:
            msg: "No se pudo cerrar la sesión en OpenShift, pero el proceso continúa."
