---
# ansible-navigator run main.yaml -i inventory.yaml --pae false --mode stdout \
# --eei quay.io/jealopez/ee-ocp:1.3 -e "@credentials.vault.yaml" --vault-password-file=vault_password

- name: Ejecutar Must Gather
  import_playbook: playbooks/generate_must_gather.yaml

- name: Subir Must Gather a Red Hat
  import_playbook: playbooks/upload_must_gather.yaml

- name: Cerrar sesión en OpenShift (revocar token)
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all.yaml
    - credentials.vault.yaml

  tasks:
    - name: Mostrar archivos y directorios en /runner/project/
      command: ls -l /runner/project/
      register: repo_content

    - name: Mostrar estructura de archivos en el repositorio
      command: find /runner/project/
      register: repo_structure

    - name: Verificar si credentials.vault.yaml está presente
      stat:
        path: /runner/project/credentials.vault.yaml
      register: vault_file

    - name: Mostrar contenido de credentials.vault.yaml (si existe)
      command: cat /runner/project/credentials.vault.yaml
      when: vault_file.stat.exists
      register: vault_content

    - name: Mostrar resultados
      debug:
        msg:
          - "Contenido del repositorio: {{ repo_content.stdout_lines }}"
          - "Estructura del repositorio: {{ repo_structure.stdout_lines }}"
          - "Contenido de credentials.vault.yaml: {{ vault_content.stdout_lines | default('Archivo no encontrado') }}"


    - name: Cerrar sesión en OpenShift
      block:
        - name: Revocar el token de sesión en OpenShift
          redhat.openshift.openshift_auth:
            state: absent
            host: "{{ openshift_api_url }}"
            api_key: "{{ openshift_api_token }}"
            validate_certs: false
          when: openshift_api_token is defined
      rescue:
        - name: Advertencia si no se puede cerrar sesión
          ansible.builtin.debug:
            msg: "No se pudo cerrar la sesión en OpenShift, pero el proceso continúa."
