- name: Retrieve case details
  ansible.builtin.uri:
    url: "{{ support_case_details_url }}"
    method: GET
    headers:
      Authorization: "Bearer {{ access_token }}"
      Accept: "application/json"
    return_content: true
  register: case_response
  failed_when: 
    - case_response.status != 200
    - case_response.json is not defined
    - "'status' not in case_response.json"

- name: Debug case details
  ansible.builtin.debug:
    msg:
      - "Case Response Status: {{ case_response.status }}"
      - "Case Response Body: {{ case_response.json | to_nice_json }}"
  when: enable_debug | default(false)

- name: Check case status
  ansible.builtin.set_fact:
    # continue_execution: "{{ case_response.json.status != 'Closed' }}"
    continue_execution: true

# - name: Stop execution if case is closed
#   ansible.builtin.fail:
#     msg: "Case {{ support_case_id }} is closed. Stopping execution."
#   when: not continue_execution
