####################################
# ansible-builder build -t ee-ocp 
####################################
---
version: 3

dependencies:
  galaxy:
    collections:
      - name: redhat.openshift
      - name: community.general
  python:
    - kubernetes
    - requests
    - tqdm
    - pyyaml
    - boto3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: configs
    dest: configs
  - src: rpm/openshift-clients-4.16.0-202410172045.p0.gcf533b5.assembly.stream.el9.x86_64.rpm
    dest: rpms    

additional_build_steps: 
  prepend_base:
    - |
      COPY _build/rpms/*.rpm /tmp/openshift-clients.rpm
      RUN microdnf install -y bash-completion && \
      rpm -ivh /tmp/openshift-clients.rpm
      RUN pip install --upgrade pip && \
      pip install requests tqdm pyyaml
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg