---
# Playbook: generate_must_gather.yaml
# Ejecutar con:
# ansible-navigator run playbooks/generate_must_gather.yaml -i inventory.yaml \
#   --pae false --mode stdout --eei quay.io/jealopez/ee-ocp:1.3 \
#   -e "@credentials.vault.yaml" --vault-password-file=vault_password

- name: Generate Must Gather Data from OpenShift
  hosts: localhost
  gather_facts: false

  # vars_files:
  #   - group_vars/all.yaml
  #   - ../credentials.vault.yaml

  roles:
    - role: auth_ocp
    - role: generate_must_gather
