---
# Playbook: upload_must_gather.yaml
#
# Ejecutar con:
# ansible-navigator run playbooks/upload_must_gather.yaml --pae false --mode stdout \
#   --eei quay.io/jealopez/ee-ocp:1.0 --vault-password-file=vault_password

- name: Upload Must Gather to Red Hat Case
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../group_vars/all.yaml
    - ../credentials.vault.yaml}

  roles:
    - role: auth_api
    - role: case_management
    - role: file_upload
    - role: validate_upload
